### ISSUE TITLE
Todo: Ajax

### ISSUE THREAD

**Issue by Dguthmann** [devtown425/NYTSearch#5]
- [ ] get api key for NYT
- [ ] Add Script Functionality for ajax request
- [ ] Create logs: showing things like titles, link to article and basic premise
